language: node_js
node_js:
     - node
before_install:
   # Repo for Yarn
   - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
   - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
   - sudo apt-get update -qq
   - sudo apt-get install -y -qq yarn=1.22.4-1
   - yarn install --no-lockfile
cache:
    yarn : true
    directories:
        - node_modules
before_script :
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH=$HOME/.yarn/bin:$PATH
script:
    -npm run test:unit             